common:
  rerun_ip: "192.168.200.0"
  dt: 0.002
  stiffness: [
    50, 50,
    20, 20, 20, 20,
    20, 20, 20, 20,
    200,
    200, 200, 200, 200, 100, 100,
    200, 200, 200, 200, 100, 100
  ]
  damping: [
    1, 1,
    0.5, 0.5, 0.5, 0.5,
    0.5, 0.5, 0.5, 0.5,
    2,
    2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2
  ]
  default_qpos: [
    0, 0,
    0.2, -1.35, 0, -0.5,
    0.2, 1.35, 0, 0.5,
    0,
    -0.2, 0, 0, 0.4, -0.25, 0,
    -0.2, 0, 0, 0.4, -0.25, 0
  ]
  torque_limit: [
    7., 7.,
    10., 10., 10., 10.,
    10., 10., 10., 10.,
    30.,
    60., 25., 30., 60., 24., 6.,
    60., 25., 30., 60., 24., 6.
  ]

policy:
  policy_path: "/home/wys/lcs/Legged_odom/deploy_odom/models/T1_run.pth"
  odom_policy_path: "/home/wys/lcs/Legged_odom/deploy_odom/models/model_wys_560_sim_0.02s_acc.pt"
  num_actions: 11
  num_observations: 83
  num_odom_obs: 32
  delta_time: 0.02
  use_accel: true
  use_pos_seq: true
  use_actions: true
  num_stack: 50
  gait_frequency: 2

  normalization:
    gravity: 1.0
    lin_vel: 1.0
    ang_vel: 1.0
    dof_pos: 1.0
    dof_vel: 0.1
    clip_actions: 1.
    base_acc: 0.1

  control:
    action_scale: 1.
    decimation: 10

mech:
  parallel_mech_indexes: [15, 16, 21, 22]

prepare:
  stiffness: [
    5., 5.,
    40., 50., 20., 10.,
    40., 50., 20., 10.,
    100., 
    350., 350., 180., 350., 450., 450.,
    350., 350., 180., 350., 450., 450.,
  ]
  damping: [
    0.1, 0.1,
    0.5, 1.5, 0.2, 0.2,
    0.5, 1.5, 0.2, 0.2,
    5.0,
    7.5, 7.5, 3., 5.5, 0.5, 0.5,
    7.5, 7.5, 3., 5.5, 0.5, 0.5,
  ]
  default_qpos: [
    0.0,  0.0,
    0.25, -1.4, 0.0, -0.5,
    0.25, 1.4, 0.0, 0.5,
    0.0,
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
    -0.1, 0.0, 0.0, 0.2, -0.1, 0.0,
  ]
